# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-11-24 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0058_processrun_rto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='origin',
            name='info',
        ),
        migrations.AddField(
            model_name='origin',
            name='agent',
            field=models.TextField(blank=True, null=True, verbose_name='所有模块'),
        ),
        migrations.AddField(
            model_name='target',
            name='agent',
            field=models.TextField(blank=True, null=True, verbose_name='所有模块'),
        ),
        migrations.AlterField(
            model_name='target',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='SQL Server账户信息'),
        ),
    ]
