# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-11-25 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0059_auto_20191124_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.Origin', verbose_name='源端'),
        ),
        migrations.AddField(
            model_name='process',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.Target', verbose_name='恢复资源'),
        ),
    ]
